# Generated by Django 5.0.1 on 2024-04-28 15:18

import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import localflavor.generic.models
import precise_bbcode.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedEditionIcecream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Тороговое наименование')),
                ('fabricator', models.CharField(max_length=40, verbose_name='Производитель')),
                ('composition', models.CharField(blank=True, max_length=500, null=True, verbose_name='Состав')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость')),
                ('package', models.CharField(choices=[('cup', 'стаканчик'), ('cone', 'рожок'), ('brick', 'брикет'), ('tube', 'туба '), ('box', 'коробка'), ('pouch', 'пакетик'), ('foil', 'фольга'), ('plastic_container', 'пластиковый контенер'), ('paper container', 'бумажный контенер'), ('balls', 'шарик')], default='balls', max_length=20, verbose_name='Упаковка')),
                ('weight', models.DecimalField(decimal_places=2, default=200.0, max_digits=6, verbose_name='Вес нетто')),
                ('expiration_date_in_days', models.IntegerField(default=30, verbose_name='Срок употребления')),
                ('vegan', models.BooleanField(default=False, verbose_name='Веганское')),
                ('sugar_free', models.BooleanField(default=False, verbose_name='Без добавления сахара')),
                ('theme', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тематика')),
                ('season', models.CharField(blank=True, max_length=50, null=True, verbose_name='Сезон/Праздник')),
                ('sale_start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала продаж')),
                ('sale_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания продаж')),
                ('unique_flavors', models.TextField(blank=True, help_text='Перечислите уникальные вкусы этой серии', null=True, verbose_name='Уникальные вкусы')),
            ],
            options={
                'verbose_name': 'Ограниченная серия мороженого',
                'verbose_name_plural': 'Ограниченная серия мороженого',
            },
        ),
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('levelname', models.CharField(max_length=15)),
                ('levelnum', models.PositiveIntegerField()),
                ('pathname', models.CharField(max_length=1024)),
                ('line', models.PositiveIntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscribes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True, verbose_name='Mейл')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implementer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Исполнитель')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор задачи')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('_description_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('description', precise_bbcode.fields.BBCodeTextField(blank=True, no_rendered_field=True, null=True, verbose_name='Описание')),
                ('deadline', models.DateField(db_index=True, verbose_name='Срок исполнения')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('n', 'Не начато'), ('d', 'Исполнено'), ('p', 'На исполнении')], default='n', max_length=1, verbose_name='Статус')),
                ('done_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата исполнения')),
                ('time_to_do', django.contrib.postgres.fields.ranges.DateTimeRangeField(null=True, verbose_name='Время на выполнение')),
                ('time_allotted', models.DurationField(blank=True, null=True, verbose_name='Отведенное время')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
            managers=[
                ('actions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Наименование продавца')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер для связи')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sub_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('country', models.CharField(choices=[('RU', 'Россия'), ('US', 'США'), ('GB', 'Великобритания'), ('GR', 'Греция')], max_length=2, verbose_name='Страна')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес проживания')),
                ('card_num', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Номер карты должен состоять ровно из 16 цифр.', regex='^\\d{16}$')], verbose_name='Номер карты')),
                ('acc_num', localflavor.generic.models.IBANField(include_countries=('RU', 'GB', 'GR'), max_length=34, use_nordea_extensions=False)),
                ('bic', localflavor.generic.models.BICField(max_length=11)),
                ('mail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_email', to='taskboard.subscribes', verbose_name='электронный адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Vendors_Icecream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('icecream_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskboard.limitededitionicecream')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskboard.vendors')),
            ],
        ),
        migrations.AddField(
            model_name='vendors',
            name='icecream_pl',
            field=models.ManyToManyField(through='taskboard.Vendors_Icecream', to='taskboard.limitededitionicecream'),
        ),
    ]
